server.port=8080
spring.application.name=proyectodam-server

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/proyectodam

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/proyecto_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



# JWT
app.jwt.secret=cGFzc3dvcmRfc2VjcmV0b19tX3NlZ3VyYV9wcm95ZWN0b0RBTTM=
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Logging
logging.level.com.proyectodam=DEBUG

# Admin middleware ← ESTO ES LO QUE FALTABA
app.admin.nickname=middleware_admin
app.admin.password=admin

